replicaCount: 1

image:
  repository: your-dockerhub-username/cloudtrackr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: cloudtrackr.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
